### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by IF-tiger** [luisbocanegra/plasma-simple-window-buttons#1]
I run `./install.sh` I received the following error
```
CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindKF6Plasma.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF6Plasma", but CMake did not find one.

  Could not find a package configuration file provided by "KF6Plasma" with
  any of the following names:

    KF6PlasmaConfig.cmake
    kf6plasma-config.cmake

  Add the installation prefix of "KF6Plasma" to CMAKE_PREFIX_PATH or set
  "KF6Plasma_DIR" to a directory containing one of the above files.  If
  "KF6Plasma" provides a separate development package or SDK, be sure it has
  been installed
```
i open kde unstable branch （opensuse）
Can you give me guidance on how to solve it? thanks

**Comment by luisbocanegra** [comment]
You need to install a package that provides it I think it's kf6-plasma-devel or something similar.

Beware that this plasmoid needs changes like https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/6117600f290960c7ddb11f52115d1bbd34b17075 to work with latest Plasma beta builds

**Comment by IT-Tagore** [comment]
> 您需要安装一个提供它的软件包，我认为它是 kf6-plasma-devel 或类似的东西。
> 
> 请注意，此等离子体需要更改 [luisbocanegra/plasma-panel-spacer-extended@6117600](https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/6117600f290960c7ddb11f52115d1bbd34b17075) 才能与最新的 Plasma beta 版本一起使用

thanks

**Comment by matiux** [comment]
Same issue on Linux Arch but I'm not finding the lib kf6-plasma-devel

@IF-tiger how have you solved?

**Comment by D3SOX** [comment]
@matiux It works on my arch machine. Do you have `kconfig` installed? (or maybe also `extra-cmake-modules`)

**Comment by luisbocanegra** [comment]
Hi everyone! Unfortunately I no longer have a need for this widget as the original window buttons widget has been ported and works great, and also because there are other qml only alternatives now that have far more features than this hard-coded attempt of mine.

This means I will probably not continue its development to focus my time on other things and also because I won't be using it. Hope you understand and thanks for trying it out.

**Comment by D3SOX** [comment]
Okay, good to know @luisbocanegra. Maybe add it to the README and archive the project then.
I was only watching this repo because it might offer something which I don't get of the other ones.
